use_frameworks!

platform :ios, '9.0'

target 'SZViewSDKPods_Example' do
  pod 'SZViewSDKPods', :path => '../'

  target 'SZViewSDKPods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
